[package]
name = "c2-beacon"
version = "0.1.0"
edition = "2024"

[dependencies]
hostname = "0.4.0"
local-ip-address = "0.6.3"
reqwest = { version = "0.12.15", features = ["blocking"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
